#!/bin/bash
# bmitune.sh for firetv/fastchannels
# 2026.09.28
#
# ah4c "start" script for FastChannels Player (com.fastchannels.player).
# Generated by FastChannels' "Export ah4c scripts" button. FASTCHANNELS_URL is
# read from ah4c's own environment.
#
# ah4c runs this asynchronously, after it's already relaying bytes from the
# encoder to whatever is consuming the tune (e.g. Channels DVR) — so it's fine
# for this to take a few seconds, unlike prebmitune.sh.
#
# The actual play trigger (resolving the channel, DRM license, and the adb
# `am start` into FastChannels Player) is already implemented server-side at
# /play/fc-player/<source>/<channel_id>.m3u8 — this script just calls that and
# confirms playback actually started, the same way ah4c's own bundled scripts
# confirm a Hulu/YouTube TV tune via `adb shell dumpsys media_session`.
#
# ah4c calls this as: bmitune.sh <channel> <tunerip>
# <channel> is FastChannels' own "source:channel_id" key (e.g. fubo:127957) —
# see the m3u FastChannels generates for ah4c's channel-id values.

set -x

STATION="$1"
TUNERIP="$2"

SOURCE="${STATION%%:*}"
CHANNEL_ID="${STATION#*:}"

# CalVer of this script set: bump to today's date whenever any script in
# firetv/fastchannels changes. Sent with every trigger so FastChannels can show
# which script version each tuner is running and flag outdated ones.
SCRIPTS_VERSION="2026.09.28"

declare -i COUNTER=0
declare -i FAILSAFE=0
STATUS="notplaying"

echo "[STARTING] bmitune.sh $STATION $TUNERIP"

if [ -z "$SOURCE" ] || [ -z "$CHANNEL_ID" ] || [ "$SOURCE" == "$CHANNEL_ID" ]; then
	echo "[ERROR] Could not parse source/channel_id from STATION='$STATION' — expected source:channel_id"
	exit 1
fi

# ah4c doesn't kill this script when the viewer disconnects — it runs
# stopbmitune.sh and lets this one finish. Left alone, an unconfirmed tune kept
# retrying for up to a minute after it was stopped, re-triggering a channel
# nobody was watching (or onto a newer tune on the same device), and could
# report [SUCCESS] off a later tune's playback. The tune file names the tune
# that currently owns this tuner; stopbmitune.sh removes it and a newer tune
# overwrites it, and either one ends this run.
TUNE_FILE="/tmp/fastchannels-tune-${TUNERIP//[^A-Za-z0-9._-]/_}"
TUNE_TOKEN="$STATION $$"
echo "$TUNE_TOKEN" > "$TUNE_FILE"

is_current_tune() {
	[ "$(cat "$TUNE_FILE" 2>/dev/null)" == "$TUNE_TOKEN" ]
}

is_media_playing() {
	# Do not accept a playing session from the Fire TV launcher, Alexa, or a
	# previous app as proof that *our* tune succeeded.  Media3 publishes the
	# package name immediately before its PlaybackState in dumpsys output.
	#
	# Accept both PlaybackState renderings: Fire OS prints "state=3", newer AOSP
	# (Google TV, onn., Chromecast) prints "state=PLAYING(3)".
	adb -s "$TUNERIP" shell dumpsys media_session 2>/dev/null | \
		grep -A 12 "package=com.fastchannels.player" | \
		grep -q -e "state=PlaybackState {state=3" -e "state=PlaybackState {state=PLAYING(3)"
}

trigger() {
	# FASTCHANNELS_URL missing or malformed is not a retry-able condition — it's
	# a container misconfiguration, and curl on a schemeless URL fails silently
	# since its exit status was never checked here. That used to mean a bad
	# config ran the full wait loop below to its 64-second timeout before saying
	# anything, indistinguishable in the log from a slow tune. Caught here
	# instead, once, before ever calling curl.
	if [[ ! "$FASTCHANNELS_URL" =~ ^https?:// ]]; then
		echo "[ERROR] FASTCHANNELS_URL is not set to a valid http(s) URL (got '$FASTCHANNELS_URL') — cannot trigger $STATION. Set FASTCHANNELS_URL in ah4c's environment."
		exit 1
	fi
	# Forward the tuner adb address ah4c allocated for this tune. FastChannels does
	# the `am start` server-side, so without this it would always trigger its single
	# configured device — wrong once ah4c is fronting more than one streaming stick.
	# Absent/empty $TUNERIP: server falls back to its configured adb address.
	local url="$FASTCHANNELS_URL/play/fc-player/$SOURCE/$CHANNEL_ID.m3u8?scripts=$SCRIPTS_VERSION"
	if [ -n "$TUNERIP" ]; then
		url="$url&adb=$TUNERIP"
	fi
	echo "[TRIGGER] $url"
	curl -s -o /dev/null --max-time 10 "$url"
}

trigger

echo -n "[WAITING] for stream to start..."
while [ "$STATUS" == "notplaying" ]; do
	sleep 1
	if ! is_current_tune; then
		echo ""
		echo "[STOPPED] $STATION was stopped or replaced by a newer tune on $TUNERIP. Not retrying."
		exit 0
	fi
	if is_media_playing; then
		STATUS="playing"
		echo ""
		echo "[SUCCESS] $STATION has started."
	else
		echo -n "."
		if ((COUNTER > 15)); then
			((FAILSAFE++))
			echo ""
			echo "[TIMEOUT] Retrying trigger ($FAILSAFE)"
			trigger
			COUNTER=0
		fi
		if ((FAILSAFE > 3)); then
			echo ""
			echo "[FAIL] Could not confirm playback for $STATION on $TUNERIP. Giving up."
			exit 1
		fi
		((COUNTER++))
	fi
done

exit 0
