#!/bin/bash
#
# ah4c "start" script for FastChannels Player (com.fastchannels.player).
# Generated by FastChannels' "Export ah4c scripts" button, with FASTCHANNELS_URL
# pre-filled to what was confirmed at export time.
#
# ah4c runs this asynchronously, after it's already relaying bytes from the
# encoder to whatever is consuming the tune (e.g. Channels DVR) — so it's fine
# for this to take a few seconds, unlike prebmitune.sh.
#
# The actual play trigger (resolving the channel, DRM license, and the adb
# `am start` into FastChannels Player) is already implemented server-side at
# /play/fc-player/<source>/<channel_id>.m3u8 — this script just calls that and
# confirms playback actually started, the same way ah4c's own bundled scripts
# confirm a Hulu/YouTube TV tune via `adb shell dumpsys media_session`.
#
# ah4c calls this as: bmitune.sh <channel> <tunerip>
# <channel> is FastChannels' own "source:channel_id" key (e.g. fubo:127957) —
# see the m3u FastChannels generates for ah4c's channel-id values.

STATION="$1"
TUNERIP="$2"

SOURCE="${STATION%%:*}"
CHANNEL_ID="${STATION#*:}"

declare -i COUNTER=0
declare -i FAILSAFE=0
STATUS="notplaying"

echo "[STARTING] bmitune.sh $STATION $TUNERIP"

if [ -z "$SOURCE" ] || [ -z "$CHANNEL_ID" ] || [ "$SOURCE" == "$CHANNEL_ID" ]; then
	echo "[ERROR] Could not parse source/channel_id from STATION='$STATION' — expected source:channel_id"
	exit 1
fi

is_media_playing() {
	# Do not accept a playing session from the Fire TV launcher, Alexa, or a
	# previous app as proof that *our* tune succeeded.  Media3 publishes the
	# package name immediately before its PlaybackState in dumpsys output.
	adb -s "$TUNERIP" shell dumpsys media_session 2>/dev/null | \
		grep -A 12 "package=com.fastchannels.player" | \
		grep -q "state=PlaybackState {state=3"
}

trigger() {
	# Forward the tuner adb address ah4c allocated for this tune. FastChannels does
	# the `am start` server-side, so without this it would always trigger its single
	# configured device — wrong once ah4c is fronting more than one streaming stick.
	# Absent/empty $TUNERIP: server falls back to its configured adb address.
	local url="$FASTCHANNELS_URL/play/fc-player/$SOURCE/$CHANNEL_ID.m3u8"
	if [ -n "$TUNERIP" ]; then
		url="$url?adb=$TUNERIP"
	fi
	echo "[TRIGGER] $url"
	curl -s -o /dev/null --max-time 10 "$url"
}

trigger

echo -n "[WAITING] for stream to start..."
while [ "$STATUS" == "notplaying" ]; do
	sleep 1
	if is_media_playing; then
		STATUS="playing"
		echo ""
		echo "[SUCCESS] $STATION has started."
	else
		echo -n "."
		if ((COUNTER > 15)); then
			((FAILSAFE++))
			echo ""
			echo "[TIMEOUT] Retrying trigger ($FAILSAFE)"
			trigger
			COUNTER=0
		fi
		if ((FAILSAFE > 3)); then
			echo ""
			echo "[FAIL] Could not confirm playback for $STATION on $TUNERIP. Giving up."
			exit 1
		fi
		((COUNTER++))
	fi
done

exit 0
