#!/bin/bash
#
# ah4c "pre" script for FastChannels Player (com.fastchannels.player).
# Generated by FastChannels' "Export ah4c scripts" button — see bmitune.sh for the
# real work; this one just has to be fast, since ah4c runs it before opening the
# encoder connection and it counts against the DVR's ~30s tune budget.
#
# ah4c calls this as: prebmitune.sh <tunerip> <channel>

TUNERIP="$1"

echo "[STARTING] prebmitune.sh $TUNERIP"

if [[ "$TUNERIP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(:[0-9]+)?$ ]]; then
	OUTPUT=$(adb connect "$TUNERIP" 2>&1)
	echo "$OUTPUT"
	if [[ "$OUTPUT" == *"unable to connect"* || "$OUTPUT" == *"failed to connect"* ]]; then
		echo "[ERROR] adb connect $TUNERIP failed"
		exit 1
	fi
fi

exit 0
