#!/bin/bash
#
# ah4c "reboot" script for FastChannels Player (com.fastchannels.player).
# Generated by FastChannels' "Export ah4c scripts" button.
#
# ah4c only runs this if stopbmitune.sh itself errors (adb unreachable, etc.) —
# a genuinely stuck device, not a normal stop. FastChannels Player is a single
# trivial Activity, so this should be rare; ah4c still requires this file to
# exist alongside the others.
#
# ah4c calls this as: reboot.sh <tunerip> <channel>

TUNERIP="$1"

echo "[REBOOT] reboot.sh $TUNERIP"
adb -s "$TUNERIP" reboot >/dev/null 2>&1

exit 0
