#!/bin/bash
#
# ah4c "stop" script for FastChannels Player (com.fastchannels.player).
# Generated by FastChannels' "Export ah4c scripts" button.
#
# ah4c runs this the moment the downstream viewer disconnects from its
# /play/tuner/<channel> stream — the real, immediate "stopped watching" signal
# for this path (FastChannels' own idle-stop watchdog, used for direct
# playback, is a slower DVR-activity poll and doesn't apply here).
#
# ah4c calls this as: stopbmitune.sh <tunerip> <channel>

TUNERIP="$1"
STATION="$2"

echo "[STOPPING] stopbmitune.sh $STATION $TUNERIP"
adb -s "$TUNERIP" shell am force-stop com.fastchannels.player >/dev/null 2>&1

exit 0
